/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;
import com.binance.api.client.domain.market.Candlestick;
import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JButton;
import javax.swing.event.TableModelListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author 8570w
 */
public class gui  extends javax.swing.JPanel  {

    private DefaultTableModel mainModel;
    private boolean DEBUG = false;
    private String interval;
    private String rateSMA20;
    private String numStick;
    private streamBTC streamData;
    
    
    /**
     * Creates new form gui
     */
    public gui()  {
        mainModel = new DefaultTableModel();
        mainModel.addColumn("Symbol");
        mainModel.addColumn("Close");
        mainModel.addColumn("Volumn");
        mainModel.addColumn("% ");
        initComponents();
        streamData = new streamBTC();
        streamData.restart("1m", 5, 0.6);
        
        for (int i = 0; i< streamData.candleStreams.size(); i++) {
            //mainModel.setValueAtRow(streamData.candleStreams.get(i).getFirst(), i);
            mainModel.addRow(streamData.candleStreams.get(i).getFirst().toArray());
        }
        
        
    }

    
    public void updateGui() {
        mainModel.setRowCount(0);
        for (int i = 0; i< streamData.candleStreams.size(); i++) {
            //mainModel.setValueAtRow(streamData.candleStreams.get(i).getFirst(), i);
            mainModel.addRow(streamData.candleStreams.get(i).getFirst().toArray());
        }
        mainModel.fireTableDataChanged();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        chooseInterval = new javax.swing.JComboBox<>();
        chooseNumStick = new javax.swing.JComboBox<>();
        chooseRateSMA20 = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        mainTable.setModel(mainModel);
        mainTable.setRowHeight(25);
        jScrollPane1.setViewportView(mainTable);

        chooseInterval.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1m", "3m", "5m", "15m", "30m", "1H", "2H", "4H", "1D" }));
        chooseInterval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseIntervalActionPerformed(evt);
            }
        });

        chooseNumStick.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "20", "30", "40" }));
        chooseNumStick.setToolTipText("");

        chooseRateSMA20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.6", "1", "2", "3", "5" }));
        chooseRateSMA20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseRateSMA20ActionPerformed(evt);
            }
        });

        btnSubmit.setText("OK");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel1.setText("Khung");

        jLabel2.setText("So cay nen >=");

        jLabel4.setText("Do rong BB <= %");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chooseInterval, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chooseNumStick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addComponent(chooseRateSMA20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(386, 386, 386)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseNumStick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseRateSMA20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chooseRateSMA20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseRateSMA20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseRateSMA20ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        this.rateSMA20 = (String)(chooseRateSMA20.getSelectedItem());
        System.out.println("SMA20:" + this.rateSMA20);
        streamData.restart((String)(chooseInterval.getSelectedItem()), Integer.parseInt((String) this.chooseNumStick.getSelectedItem()), Double.valueOf((String) this.chooseRateSMA20.getSelectedItem()).doubleValue());
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void chooseIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseIntervalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseIntervalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> chooseInterval;
    private javax.swing.JComboBox<String> chooseNumStick;
    private javax.swing.JComboBox<String> chooseRateSMA20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        JFrame frame = new JFrame("Coin Lookup");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Container contentPane = frame.getContentPane();

        gui Gui = new gui();
        frame.add(Gui);

        // set the size of the frame 300 x 200
        frame.setBounds(50, 50, 600, 650);
        frame.setVisible(true);
        
        
        while(true) {
            Gui.updateGui();
            try
            {
                Thread.sleep(5000);
            }
            catch(InterruptedException ex)
            {
                Thread.currentThread().interrupt();
            }
        }
        
        
      }


}

